# Generated by Django 5.0.6 on 2024-05-10 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtb_v4_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'History'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name_plural': 'Media'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name_plural': 'Page'},
        ),
    ]
