# Generated by Django 5.0.6 on 2024-05-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtb_v4_app', '0002_alter_history_options_alter_media_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=255),
        ),
    ]
