# Generated by Django 5.0.6 on 2024-06-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtb_v4_app', '0003_alter_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('image', 'Poster'), ('video', 'Video')], max_length=255),
        ),
    ]
